# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: currency/model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63urrency/model.proto\"\x99\x02\n\x08\x43urrency\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0b\n\x03iso\x18\x02 \x01(\t\x12\x15\n\rcurrency_name\x18\x03 \x01(\t\x12\x13\n\x0bis_obsolete\x18\x04 \x01(\x08\x12\x1a\n\rsuperseded_by\x18\x05 \x01(\tH\x00\x88\x01\x01\x12\x1c\n\x0f\x63urrency_symbol\x18\x06 \x01(\tH\x01\x88\x01\x01\x12%\n\x18\x63urrency_symbol_on_right\x18\x07 \x01(\x08H\x02\x88\x01\x01\x12\x16\n\tcreate_at\x18\x08 \x01(\x02H\x03\x88\x01\x01\x42\x10\n\x0e_superseded_byB\x12\n\x10_currency_symbolB\x1b\n\x19_currency_symbol_on_rightB\x0c\n\n_create_at\" \n\x12GetCurrencyRequest\x12\n\n\x02id\x18\x01 \x01(\r\"\x8c\x01\n\x14GetCurrenciesRequest\x12\x12\n\x05limit\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x18\n\x0bis_obsolete\x18\x02 \x01(\x08H\x01\x88\x01\x01\x12\x1a\n\rsuperseded_by\x18\x03 \x01(\tH\x02\x88\x01\x01\x42\x08\n\x06_limitB\x0e\n\x0c_is_obsoleteB\x10\n\x0e_superseded_by\"\xf1\x01\n\x12\x41\x64\x64\x43urrencyRequest\x12\x0b\n\x03iso\x18\x01 \x01(\t\x12\x15\n\rcurrency_name\x18\x02 \x01(\t\x12\x13\n\x0bis_obsolete\x18\x03 \x01(\x08\x12\x1a\n\rsuperseded_by\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x1c\n\x0f\x63urrency_symbol\x18\x05 \x01(\tH\x01\x88\x01\x01\x12%\n\x18\x63urrency_symbol_on_right\x18\x06 \x01(\x08H\x02\x88\x01\x01\x42\x10\n\x0e_superseded_byB\x12\n\x10_currency_symbolB\x1b\n\x19_currency_symbol_on_right\"2\n\x13GetCurrencyResponse\x12\x1b\n\x08\x63urrency\x18\x01 \x01(\x0b\x32\t.Currency\"4\n\x15GetCurrenciesResponse\x12\x1b\n\x08\x63urrency\x18\x01 \x03(\x0b\x32\t.Currency2\xc6\x01\n\x10\x43urrencyServices\x12\x38\n\x0bGetCurrency\x12\x13.GetCurrencyRequest\x1a\x14.GetCurrencyResponse\x12>\n\rGetCurrencies\x12\x15.GetCurrenciesRequest\x1a\x16.GetCurrenciesResponse\x12\x38\n\x0b\x41\x64\x64\x43urrency\x12\x13.AddCurrencyRequest\x1a\x14.GetCurrencyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'currency.model_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CURRENCY']._serialized_start=25
  _globals['_CURRENCY']._serialized_end=306
  _globals['_GETCURRENCYREQUEST']._serialized_start=308
  _globals['_GETCURRENCYREQUEST']._serialized_end=340
  _globals['_GETCURRENCIESREQUEST']._serialized_start=343
  _globals['_GETCURRENCIESREQUEST']._serialized_end=483
  _globals['_ADDCURRENCYREQUEST']._serialized_start=486
  _globals['_ADDCURRENCYREQUEST']._serialized_end=727
  _globals['_GETCURRENCYRESPONSE']._serialized_start=729
  _globals['_GETCURRENCYRESPONSE']._serialized_end=779
  _globals['_GETCURRENCIESRESPONSE']._serialized_start=781
  _globals['_GETCURRENCIESRESPONSE']._serialized_end=833
  _globals['_CURRENCYSERVICES']._serialized_start=836
  _globals['_CURRENCYSERVICES']._serialized_end=1034
# @@protoc_insertion_point(module_scope)
