# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: course/model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63ourse/model.proto\"X\n\x06\x43ourse\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x63ourse\x18\x03 \x01(\x02\x12\x16\n\tcreate_at\x18\x04 \x01(\x02H\x00\x88\x01\x01\x42\x0c\n\n_create_at\"\x1e\n\x10GetCourseRequest\x12\n\n\x02id\x18\x01 \x01(\r\"\"\n\x11GetCoursesRequest\x12\r\n\x05limit\x18\x01 \x01(\r\"0\n\x10\x41\x64\x64\x43ourseRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x63ourse\x18\x02 \x01(\x02\"N\n\x11\x43\x61lcCourseRequest\x12\x1b\n\x13\x66irst_currency_name\x18\x01 \x01(\t\x12\x1c\n\x14second_currency_name\x18\x02 \x01(\t\",\n\x11GetCourseResponse\x12\x17\n\x06\x63ourse\x18\x01 \x01(\x0b\x32\x07.Course\"-\n\x12GetCoursesResponse\x12\x17\n\x06\x63ourse\x18\x01 \x03(\x0b\x32\x07.Course2\xe4\x01\n\rCourseService\x12\x32\n\tGetCourse\x12\x11.GetCourseRequest\x1a\x12.GetCourseResponse\x12\x35\n\nGetCourses\x12\x12.GetCoursesRequest\x1a\x13.GetCoursesResponse\x12\x32\n\tAddCourse\x12\x11.AddCourseRequest\x1a\x12.GetCourseResponse\x12\x34\n\nCalcCourse\x12\x12.CalcCourseRequest\x1a\x12.GetCourseResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'course.model_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_COURSE']._serialized_start=22
  _globals['_COURSE']._serialized_end=110
  _globals['_GETCOURSEREQUEST']._serialized_start=112
  _globals['_GETCOURSEREQUEST']._serialized_end=142
  _globals['_GETCOURSESREQUEST']._serialized_start=144
  _globals['_GETCOURSESREQUEST']._serialized_end=178
  _globals['_ADDCOURSEREQUEST']._serialized_start=180
  _globals['_ADDCOURSEREQUEST']._serialized_end=228
  _globals['_CALCCOURSEREQUEST']._serialized_start=230
  _globals['_CALCCOURSEREQUEST']._serialized_end=308
  _globals['_GETCOURSERESPONSE']._serialized_start=310
  _globals['_GETCOURSERESPONSE']._serialized_end=354
  _globals['_GETCOURSESRESPONSE']._serialized_start=356
  _globals['_GETCOURSESRESPONSE']._serialized_end=401
  _globals['_COURSESERVICE']._serialized_start=404
  _globals['_COURSESERVICE']._serialized_end=632
# @@protoc_insertion_point(module_scope)
