"""add created_at fields

Revision ID: 03bb6f684c1a
Revises: a44c41d47965
Create Date: 2023-07-13 19:24:44.814388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03bb6f684c1a'
down_revision = 'a44c41d47965'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cross_course', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('currency', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currency', 'created_at')
    op.drop_column('cross_course', 'created_at')
    # ### end Alembic commands ###
