"""Create table currency

Revision ID: 51bb997738f0
Revises: 
Create Date: 2023-07-13 10:52:04.784163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51bb997738f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iso', sa.String(length=40), nullable=False),
    sa.Column('currency_name', sa.String(length=100), nullable=False),
    sa.Column('is_obsolete', sa.Boolean(), nullable=True),
    sa.Column('superseded_by', sa.String(), nullable=False),
    sa.Column('currency_symbol', sa.String(), nullable=False),
    sa.Column('currency_symbol_on_right', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currency')
    # ### end Alembic commands ###
