"""Change currency table nullable state fo some fields

Revision ID: cf7a72c4d543
Revises: 4fd9a7aac0bb
Create Date: 2023-07-13 14:22:49.298495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf7a72c4d543'
down_revision = '4fd9a7aac0bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currency', 'is_obsolete',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('currency', 'superseded_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('currency', 'currency_symbol',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currency', 'currency_symbol',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('currency', 'superseded_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('currency', 'is_obsolete',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
